ESHOP/Controllers/OrderController.cs
using System.Security.Claims;
using ESHOP.Models;
using ESHOP.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ZarinpalSandbox;

namespace ESHOP.Controllers;

public class OrderController : Controller
{
    private readonly IOrderService _orderService;
    private readonly IProductService _productService;
    public OrderController(IOrderService orderService, IProductService productService)
    {
        _orderService = orderService;
        _productService = productService;
    }

    [Authorize]
    public IActionResult AddToCart(int itemId)
    {
        var product = _productService.GetProductIncludeItem(itemId);
        if (product != null)
        {
            var userId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier).ToString());
            var order = _orderService.GetOrderByUserId(userId);

            if (order != null)
            {
                var orderDetail = _orderService.GetOrderDetailByProductId(itemId, order.OrderId);
                if (orderDetail != null)
                {
                    orderDetail.Count += 1;
                }
                else
                {
                    _orderService.InsertOrderDetail(new OrderDetail()
                    {
                        OrderId = order.OrderId,
                        Price = product.Item.Price,
                        ProductId = product.Id,
                        Count = 1
                    });
                }
            }
            else
            {
                order = new Order()
                {
                    UserId = userId,
                    CreateDate = DateTime.Now,
                    IsOrderFinished = false,
                };
                _orderService.InsertOrder(order);
                _orderService.Save();
                _orderService.InsertOrderDetail(new OrderDetail()
                {
                    OrderId = order.OrderId,
                    Price = product.Item.Price,
                    ProductId = product.Id,
                    Count = 1
                });
            }
        }
        _orderService.Save();
        return RedirectToAction("ShowCart");
    }

    [Authorize]
    public IActionResult ShowCart()
    {
        var userId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier).ToString());
        var order = _orderService.GetOrderIncludeDetailAndProduct(userId);

        return View(order);
    }
    [Authorize]
    public IActionResult RemoveItemFromCart(int detailId)
    {
        var orderDetail = _orderService.GetOrderDetail(detailId);
        if (orderDetail.Count > 1)
        {
            orderDetail.Count -= 1;
        }
        else
        {
            _orderService.DeleteOrderDetail(orderDetail);
        }
        _orderService.Save();
        
        return RedirectToAction("ShowCart");
    }

    [Authorize]
    public IActionResult Payment()
    {
        int userId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
        var order = _orderService.GetOrderIncludeDetails(userId);
        if (order == null)
            return NotFound();

        var payment = new Payment((int)order.Details.Sum(d => d.Price));
        var res = payment.PaymentRequest($"پرداخت فاکتور شماره {order.OrderId}",
            "http://localhost:44373/Home/OnlinePayment/" + order.OrderId, User.Identity.Name, User.FindFirst("PhoneNumber").Value);
        if (res.Result.Status == 100) 
            return Redirect("https://sandbox.zarinpal.com/pg/StartPay/" + res.Result.Authority);
        
        else
            return BadRequest();
            

    }

    public IActionResult OnlinePayment(int id)
    {
        if (HttpContext.Request.Query["Status"] != "" &&
            HttpContext.Request.Query["Status"].ToString().ToLower() == "ok" &&
            HttpContext.Request.Query["Authority"] != "")
        {
            string authority = HttpContext.Request.Query["Authority"].ToString();
            var order = _orderService.GetOrderByOrderId(id);
            var payment = new Payment((int)order.Details.Sum(d => d.Price));
            var res = payment.Verification(authority).Result;
            if (res.Status == 100)
            {
                order.IsOrderFinished = true;
                _orderService.UpdateOrder(order);
                _orderService.Save();
                ViewBag.code = res.RefId;
                return View();
            }
        }
        return NotFound();
    }
}

ESHOP/Controllers/ProductController.cs
using ESHOP.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace ESHOP.Controllers;

public class ProductController : Controller
{
    IProductService _productService;

    public ProductController(IProductService productService) => _productService = productService;

    [Route("/Groups/{id}/{name}")]
    public IActionResult ShowProductsByGroupId(int id,  string name)
    {
        ViewData["GroupName"] = name;
        var products = _productService.GetCategoryProducts(id);
        return View(products);
    }
}

ESHOP/Views/Shared/_Groups.cshtml
@using ESHOP.Services.Interfaces
@inject IProductService ProductService

<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        گروه ها
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
        @foreach (var item in ProductService.GetAllCategories())
        {
            <a class="dropdown-item"
               asp-controller="Product" 
               asp-action="ShowProductsByGroupId" 
               asp-route-id="@item.Id"
               asp-route-name="@item.Name">@item.Name</a>
        }
    </div>
</li>

ESHOP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"]</title>
    @* <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/> *@
    <link rel="stylesheet" href="~/css/bootstrap-rtl.css">
    <link href="https://cdn.rawgit.com/rastikerdar/sahel-font/v1.0.0-alpha23/dist/font-face.css" rel="stylesheet" type="text/css" />
</head>
<body class="rtl" style="font-family: Sahel,sans-serif;">
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">فروشگاه من</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">خانه</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ContactUs">تماس با ما</a>
                    </li>
                    <partial name="_Groups"/>
                    
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="ShowCart">سبد خرید</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark">@User.FindFirst("FullName").Value خوش آمدید</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">خروج</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">ثبت نام</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">ورود به سایت</a>
                        </li>
                    }
                    @if (User.Identity.IsAuthenticated && bool.Parse(User.FindFirst("IsAdmin").Value))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-page="/Admin/Index">پنل ادمین</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <div class="row">
        <div class="col-md-3">
            
            <div class="sidenav">
                @await Component.InvokeAsync("CategoryComponent")
            </div>

        </div>
        <div class="col-md-9">
            @RenderBody()
        </div>
    </div>
</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>
</html>

ESHOP/Views/Shared/_ProductBox.cshtml
@model ESHOP.Models.Product

<div class="col-md-4">
    <div class="card">
        <img class="card-img-top" src="/images/@(Model.Id).jpg" width="160" height="200">
        <div class="card-body">
            <h5 class="card-title">@Model.Name</h5>
            <a asp-action="Detail" 
               asp-controller="Home" 
               asp-route-id="@Model.Id" class="btn btn-outline-info">نمایش جزئیات</a>
        </div>
    </div>
</div>